import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import crypto from "crypto";

function formatDate(date: Date | string) {
  return new Date(date).toLocaleDateString("en-GB");
}

export async function exportToPDF(transactions: any[], accountId?: string) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let page = pdfDoc.addPage([842, 595]); // A4 landscape
  const { width, height } = page.getSize();
  const margin = 50;
  let y = height - 80; // Start further down for proper top margin

  const rowHeight = 30;
  const headerHeight = 35;

  // Define column positions with better spacing
  const colWidths = [100, 180, 100, 120, 100];
  const colX = [margin];
  for (let i = 0; i < colWidths.length; i++) {
    colX.push(colX[i] + colWidths[i]);
  }

  const headers = ["Date", "Description", "Amount", "Category", "Type"];

  // ===== TITLE SECTION =====
  // Draw title with proper spacing
  page.drawText("Spendix – Transactions Report", {
    x: margin,
    y: y,
    size: 20,
    font: boldFont,
    color: rgb(0.1, 0.1, 0.1),
  });

  y -= 50; // Space between title and table

  // ===== TABLE HEADER =====
  // Draw header background with slightly rounded appearance
  page.drawRectangle({
    x: colX[0],
    y: y - headerHeight + 8,
    width: colX[colX.length - 1] - colX[0],
    height: headerHeight,
    color: rgb(0.85, 0.87, 0.95), // Soft blue-gray header
    borderColor: rgb(0.7, 0.72, 0.8),
    borderWidth: 1,
  });

  // Draw header text with bold font
  headers.forEach((h, i) => {
    page.drawText(h, {
      x: colX[i] + 8,
      y: y - 8,
      size: 11,
      font: boldFont,
      color: rgb(0.2, 0.2, 0.3),
    });
  });

  // Draw vertical separators in header
  for (let i = 1; i < colX.length - 1; i++) {
    page.drawLine({
      start: { x: colX[i], y: y + 5 },
      end: { x: colX[i], y: y - headerHeight + 8 },
      thickness: 1,
      color: rgb(0.7, 0.72, 0.8),
    });
  }

  y -= headerHeight;

  // ===== DATA ROWS =====
  for (let idx = 0; idx < transactions.length; idx++) {
    const tx = transactions[idx];

    // Determine row background color
    const bgColor =
      tx.type === "INCOME"
        ? rgb(0.85, 0.98, 0.85) // Light green
        : tx.type === "EXPENSE"
          ? rgb(1, 0.88, 0.88) // Light red/pink
          : rgb(1, 1, 1); // White

    // Draw row background
    page.drawRectangle({
      x: colX[0],
      y: y - rowHeight + 8,
      width: colX[colX.length - 1] - colX[0],
      height: rowHeight,
      color: bgColor,
      borderColor: rgb(0.85, 0.85, 0.85),
      borderWidth: 0.5,
    });

    // Draw cell text with proper padding
    const textY = y - 12;
    page.drawText(formatDate(tx.date), {
      x: colX[0] + 8,
      y: textY,
      size: 10,
      font,
      color: rgb(0.2, 0.2, 0.2),
    });

    const description = tx.description ?? "-";
    const truncatedDesc =
      description.length > 28
        ? description.substring(0, 25) + "..."
        : description;
    page.drawText(truncatedDesc, {
      x: colX[1] + 8,
      y: textY,
      size: 10,
      font,
      color: rgb(0.2, 0.2, 0.2),
    });

    page.drawText(`${Number(tx.amount).toFixed(2)}`, {
      x: colX[2] + 8,
      y: textY,
      size: 10,
      font,
      color: rgb(0.2, 0.2, 0.2),
    });

    page.drawText(tx.category ?? "-", {
      x: colX[3] + 8,
      y: textY,
      size: 10,
      font,
      color: rgb(0.2, 0.2, 0.2),
    });

    page.drawText(tx.type ?? "-", {
      x: colX[4] + 8,
      y: textY,
      size: 10,
      font: boldFont,
      color: rgb(0.2, 0.2, 0.2),
    });

    // Draw vertical cell separators (subtle)
    for (let i = 1; i < colX.length - 1; i++) {
      page.drawLine({
        start: { x: colX[i], y: y + 5 },
        end: { x: colX[i], y: y - rowHeight + 8 },
        thickness: 0.5,
        color: rgb(0.9, 0.9, 0.9),
      });
    }

    y -= rowHeight;

    // Add new page if needed
    if (y < 80) {
      // Draw footer on current page
      page.drawText(
        `Generated by Spendix • ${new Date().toLocaleDateString("en-GB")}`,
        {
          x: width - 280,
          y: 30,
          size: 9,
          font,
          color: rgb(0.5, 0.5, 0.5),
        },
      );

      page.drawText(`Page ${pdfDoc.getPageCount()}`, {
        x: margin,
        y: 30,
        size: 9,
        font,
        color: rgb(0.5, 0.5, 0.5),
      });

      // Create new page
      page = pdfDoc.addPage([842, 595]);
      y = height - 80;

      // Redraw title on new page
      page.drawText("Spendix – Transactions Report (continued)", {
        x: margin,
        y: y,
        size: 18,
        font: boldFont,
        color: rgb(0.1, 0.1, 0.1),
      });

      y -= 50;

      // Redraw header
      page.drawRectangle({
        x: colX[0],
        y: y - headerHeight + 8,
        width: colX[colX.length - 1] - colX[0],
        height: headerHeight,
        color: rgb(0.85, 0.87, 0.95),
        borderColor: rgb(0.7, 0.72, 0.8),
        borderWidth: 1,
      });

      headers.forEach((h, i) => {
        page.drawText(h, {
          x: colX[i] + 8,
          y: y - 8,
          size: 11,
          font: boldFont,
          color: rgb(0.2, 0.2, 0.3),
        });
      });

      for (let i = 1; i < colX.length - 1; i++) {
        page.drawLine({
          start: { x: colX[i], y: y + 5 },
          end: { x: colX[i], y: y - headerHeight + 8 },
          thickness: 1,
          color: rgb(0.7, 0.72, 0.8),
        });
      }

      y -= headerHeight;
    }
  }

  // ===== FOOTER ON LAST PAGE =====
  page.drawText(
    `Generated by Spendix • ${new Date().toLocaleDateString("en-GB")}`,
    {
      x: width - 280,
      y: 30,
      size: 9,
      font,
      color: rgb(0.5, 0.5, 0.5),
    },
  );

  page.drawText(`Page ${pdfDoc.getPageCount()}`, {
    x: margin,
    y: 30,
    size: 9,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });

  const pdfBytes = await pdfDoc.save();
  const base64Data = Buffer.from(pdfBytes).toString("base64");

  const filename = accountId
    ? `spendix_transactions_${accountId}.pdf`
    : `spendix_transactions_${crypto.randomUUID()}.pdf`;

  return { data: base64Data, mime: "application/pdf", filename };
}
