export const ErrorCode = {
  UNAUTHORIZED: "UNAUTHORIZED",
  USER_NOT_FOUND: "USER_NOT_FOUND",

  INVALID_FORM_DATA: "INVALID_FORM_DATA",

  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  PRO_FEATURE_REQUIRED: "PRO_FEATURE_REQUIRED",
  PREMIUM_FEATURE_REQUIRED: "PREMIUM_FEATURE_REQUIRED",
  TRANSACTION_UPDATE_FAILED: "TRANSACTION_UPDATE_FAILED",
  TRANSACTION_DELETE_FAILED: "TRANSACTION_DELETE_FAILED",
  TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND",
  TRANSACTION_FETCH_FAILED: "TRANSACTION_FETCH_FAILED",
  ACCOUNTS_FETCH_FAILED: "ACCOUNTS_FETCH_FAILED",

  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  LAST_DEFAULT_ACCOUNT: "LAST_DEFAULT_ACCOUNT",
  ACCOUNT_ALREADY_DEFAULT: "ACCOUNT_ALREADY_DEFAULT",
  INVALID_BALANCE: "INVALID_BALANCE",
  ACCOUNT_CREATION_FAILED: "ACCOUNT_CREATION_FAILED",
  ACCOUNT_UPDATE_FAILED: "ACCOUNT_UPDATE_FAILED",
  ACCOUNT_DELETE_FAILED: "ACCOUNT_DELETE_FAILED",

  BUDGET_NOT_FOUND: "BUDGET_NOT_FOUND",
  BUDGET_CREATION_FAILED: "BUDGET_CREATION_FAILED",
  BUDGET_UPDATE_FAILED: "BUDGET_UPDATE_FAILED",
  BUDGET_FETCH_FAILED: "BUDGET_FETCH_FAILED",

  AI_RECEIPT_LIMIT_REACHED: "AI_RECEIPT_LIMIT_REACHED",
  BULK_RECEIPT_NOT_ALLOWED: "BULK_RECEIPT_NOT_ALLOWED",
  NO_TRANSACTIONS_FOR_BULK_SCAN: "NO_TRANSACTIONS_FOR_BULK_SCAN",
  DUPLICATE_TRANSACTION: "DUPLICATE_TRANSACTION",

  RECEIPT_UNREADABLE: "RECEIPT_UNREADABLE",

  IMPORT_JOB_ID_NOT_FOUND: "IMPORT_JOB_ID_NOT_FOUND",
  IMPORT_JOB_UPDATE_FAILED: "IMPORT_JOB_UPDATE_FAILED",
  IMPORT_JOB_ALREADY_PROCESSED: "IMPORT_JOB_ALREADY_PROCESSED",

  RATE_LIMITED: "RATE_LIMITED",
};

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
