export const ErrorCode = {
  UNAUTHORIZED: "UNAUTHORIZED",
  USER_NOT_FOUND: "USER_NOT_FOUND",

  INVALID_FORM_DATA: "INVALID_FORM_DATA",

  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  PRO_FEATURE_REQUIRED: "PRO_FEATURE_REQUIRED",
  TRANSACTION_CREATION_FAILED: "TRANSACTION_CREATION_FAILED",
  TRANSACTION_UPDATE_FAILED: "TRANSACTION_UPDATE_FAILED",
  TRANSACTION_DELETE_FAILED: "TRANSACTION_DELETE_FAILED",
  TRANSACTION_NOT_FOUND_TO_DELETE: "TRANSACTION_NOT_FOUND_TO_DELETE",

  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  LAST_DEFAULT_ACCOUNT: "LAST_DEFAULT_ACCOUNT",
  ACCOUNT_ALREADY_DEFAULT: "ACCOUNT_ALREADY_DEFAULT",
  INVALID_BALANCE: "INVALID_BALANCE",
  ACCOUNT_CREATION_FAILED: "ACCOUNT_CREATION_FAILED",
  ACCOUNT_UPDATE_FAILED: "ACCOUNT_UPDATE_FAILED",
  ACCOUNT_DELETE_FAILED: "ACCOUNT_DELETE_FAILED",

  BUDGET_NOT_FOUND: "BUDGET_NOT_FOUND",

  RATE_LIMITED: "RATE_LIMITED",
};

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
