// config/plan-features.ts
import { PlanType } from "@prisma/client";
import { FEATURES, FeatureKey } from "./features";

export const PLAN_FEATURES: Record<PlanType, FeatureKey[]> = {
  FREE: [],

  PRO: [
    FEATURES.RECURRING_TRANSACTIONS,
    FEATURES.AI_RECEIPT_SCAN,
    FEATURES.BUDGET_ALERT_EMAILS,
    FEATURES.AI_SEPENDING_INSIGHTS,
  ],

  PREMIUM: [
    FEATURES.RECURRING_TRANSACTIONS,
    FEATURES.AI_RECEIPT_SCAN,
    FEATURES.BUDGET_ALERT_EMAILS,
    FEATURES.AI_SEPENDING_INSIGHTS,
    FEATURES.MULTIPLE_ACCOUNTS,
    FEATURES.AI_FINANCE_CHATBOT,
    FEATURES.CSV_EXCEL_EXPORT,
    FEATURES.AI_BULK_INSERT,
  ],
};
